enum ETodoActions {
  FETCH_SINGLE_TODO = 'FETCH_SINGLE_TODO',
  FETCH_SINGLE_TODO_REQUEST = 'FETCH_SINGLE_TODO_REQUEST',
  FETCH_SINGLE_TODO_SUCCESS = 'FETCH_SINGLE_TODO_SUCCESS',
  FETCH_SINGLE_TODO_FAILURE = 'FETCH_SINGLE_TODO_FAILURE',
}

export { ETodoActions };
